name: MediBook CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore MediBook
      run: dotnet restore AppointmentSystem.Web/MediBook.csproj

    - name: Build MediBook
      run: dotnet build AppointmentSystem.Web/MediBook.csproj --no-restore

    - name: Restore Tests
      run: dotnet restore Medibook.Tests/Medibook.Tests.csproj

    - name: Run unit tests
      run: dotnet test Medibook.Tests/Medibook.Tests.csproj --verbosity normal